const puppeteer = require("puppeteer");
const path = require("path");

/**
 * Generate premium business audit PDF
 */
async function generatePDF(companyName, reportContent) {
  try {
    const browser = await puppeteer.launch({
      headless: true,
    });

    const page = await browser.newPage();

    // Format markdown headings
    const formattedContent = reportContent
      .replace(/^# (.*$)/gim, "<h1>$1</h1>")
      .replace(/^## (.*$)/gim, "<h2>$1</h2>")
      .replace(/\n/g, "<br>");

    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <style>
        * {
          box-sizing: border-box;
        }

        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background: #f5f7fb;
          color: #1f2937;
        }

        .container {
          padding: 40px;
        }

        .hero {
          background: linear-gradient(135deg, #4f46e5, #7c3aed);
          color: white;
          padding: 50px 40px;
          border-radius: 18px;
          margin-bottom: 30px;
        }

        .hero h1 {
          margin: 0;
          font-size: 34px;
        }

        .hero p {
          margin-top: 12px;
          opacity: 0.9;
          font-size: 16px;
        }

        .summary-grid {
          display: flex;
          gap: 20px;
          margin-bottom: 30px;
        }

        .summary-card {
          flex: 1;
          background: white;
          padding: 20px;
          border-radius: 14px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }

        .summary-card h3 {
          margin: 0;
          color: #6d28d9;
          font-size: 16px;
        }

        .summary-card p {
          font-size: 28px;
          margin-top: 10px;
          font-weight: bold;
        }

        .report-section {
          background: white;
          padding: 24px;
          border-radius: 16px;
          margin-bottom: 24px;
          box-shadow: 0 4px 10px rgba(0,0,0,0.06);
        }

        .report-section h1 {
          color: #4f46e5;
          font-size: 24px;
          margin-bottom: 16px;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 10px;
        }

        .report-section h2 {
          color: #7c3aed;
          margin-top: 24px;
        }

        .report-section p,
        .report-section li {
          font-size: 15px;
          line-height: 1.8;
          color: #374151;
        }

        .footer {
          margin-top: 50px;
          text-align: center;
          color: #6b7280;
          font-size: 13px;
        }

        .badge {
          display: inline-block;
          background: #ede9fe;
          color: #6d28d9;
          padding: 6px 14px;
          border-radius: 999px;
          font-size: 13px;
          margin-top: 12px;
        }

      </style>
    </head>

    <body>
      <div class="container">

        <div class="hero">
          <h1>${companyName} AI Business Audit</h1>

          <p>
            Personalized AI-powered strategic audit and digital growth recommendations.
          </p>

          <div class="badge">
            Generated by SimplifIQ AI
          </div>
        </div>

        <div class="summary-grid">
          <div class="summary-card">
            <h3>AI Readiness Score</h3>
            <p>82%</p>
          </div>

          <div class="summary-card">
            <h3>Digital Maturity</h3>
            <p>Advanced</p>
          </div>

          <div class="summary-card">
            <h3>Automation Potential</h3>
            <p>High</p>
          </div>
        </div>

        <div class="report-section">
          ${formattedContent}
        </div>

        <div class="footer">
          © 2026 SimplifIQ AI — Automated Business Intelligence Platform
        </div>

      </div>
    </body>
    </html>
    `;

    await page.setContent(htmlContent, {
      waitUntil: "domcontentloaded",
    });

    const filePath = path.join(
      __dirname,
      "../generated-reports",
      `${companyName}-report.pdf`
    );

    await page.pdf({
      path: filePath,
      format: "A4",
      printBackground: true,
      margin: {
        top: "20px",
        bottom: "20px",
        left: "20px",
        right: "20px",
      },
    });

    await browser.close();

    return filePath;
  } catch (error) {
    console.error("Error generating PDF:", error.message);
    throw new Error("Failed to generate PDF.");
  }
}

module.exports = { generatePDF };